### ISSUE TITLE
Proxy times out when connecting over LAN

### ISSUE THREAD

**Issue by reeseovine** [kizzx2/docker-wireguard-socks-proxy#6]
I'm having trouble using the proxy over my local network. When I run the command

`curl --socks5 127.0.0.1:1080 https://api.ipify.org`

from the computer running the container I get the expected result, but if I run

`curl --socks5 192.168.0.28:1080 https://api.ipify.org`

from that computer or another on the same network it times out after about a minute with this error:

`curl: (28) Failed to connect to 192.168.0.28 port 1080: Connection timed out`

The port is open but it appears to leave connections hanging when they come through the machine's LAN IP address.

**Comment by zeyugao** [comment]
Same issue here, have you figured it out?

**Comment by reeseovine** [comment]
@zeyugao  nope, but i ended up switching to [gluetun](https://github.com/qdm12/gluetun/) instead which does everything i needed it to do!

**Comment by K0IN** [comment]
The problem (at least in my setup) was, the docker network MTU, you can set it inside a compose file (or globally in docker) checkout [my fork](https://github.com/K0IN/docker-wireguard-socks-proxy/blob/main/docker-compose.yml) where I have an example on how to fix it.

**Comment by Tekka90** [comment]
Am also having the same issue... Scratching my head for few hours now... Tried the network with lower mtu, but didn't help... Is it working for someone ??

**Comment by K0IN** [comment]
try change the internal ip inside the sockd.conf, you can bind to a ip(0.0.0.0) instead of interface(eth0), i will Provider more info when i got time.

check this https://github.com/Lozy/danted/issues/18#issuecomment-303126008

(not tested btw)

**Comment by Tekka90** [comment]
Hi Koin,
This was indeed the first thing I tried 😊 but did not help.
I continued scratching my head and found a solution. You need to route the external network using iptable inside the container...
I did a fork containing that plus the capacity to manage multiple connexions...
https://github.com/Tekka90/docker-wireguard-socks-proxy

**Comment by UFervor** [comment]
> Hi Koin,
> 
> This was indeed the first thing I tried 😊 but did not help.
> 
> I continued scratching my head and found a solution. You need to route the external network using iptable inside the container...
> 
> I did a fork containing that plus the capacity to manage multiple connexions...
> 
> https://github.com/Tekka90/docker-wireguard-socks-proxy

It also works for me! Much Thanks.

**Comment by yasuoiwakura** [comment]
Hi there, i want to share some really really awkward behavior I worked around today:

my docker lxc is running as 192.168.0.201 in LAN, serving several services flawlessly

in the wireguard-proxy docker container:
Once the wg tunnel is up, dante=sockd and also netcat=nc cannot receive ANY traffic via 192.168.0.201 even though mapping is done correctly.

docker container:
netstat -tulp is showing sockd listening on 0.0.0.0:1080

docker host:
docker-proxy is listening on 0.0.0.0:1080

This is ALSO true when trying from the docker host itself.
weirdly, the docker host CAN connect through the docker network ip AND through localhost.


the mtu setting did not help, using the forked image did not help, and I was also not able to recreate the image using only the github Dockerfile etc.
changing the sockd.conf from listening eth to listening 0.0.0.0 port=1080 did also not help

my anonymized wg0.conf:
```
[Interface]
PrivateKey = foobar=
Address = 192.168.1.203/24,ffff:0000:bbbb::203/64
DNS = 192.168.1.1,ffff:0000:bbbb::aaaa:rrrr:ffff:0000
DNS = fritz.box

[Peer]
PublicKey = foobar=
PresharedKey = foobar=
AllowedIPs = 192.168.1.0/24,0.0.0.0/0,ffff:0000:bbbb::/64,::/0
Endpoint = foobar.myfritz.net:50324
PersistentKeepalive = 25
```


And my personal solution by adding socat to the docker-compose.yml:
```
version: '3.7'
#name: wireguard-foobar
services:
    wgsock:
        image: ghcr.io/k0in/docker-wireguard-socks-proxy:latest
        container_name: wireguard-foobar-dante

        restart: always
        network_mode: "wireguard-foobar_default"
        ports:
            - "1080:1080"
        volumes:
            - ./data:/etc/wireguard/:ro # path to your config
        cap_add:
            - NET_ADMIN
    socat:
        container_name: wireguard-foobar-socat
        network_mode: "wireguard-foobar_default"
        ports:
            - 1081:1081
        image: alpine/socat
        command: TCP-LISTEN:1081,fork TCP:wireguard-foobar-dante:1080
```
works for me, since I could not reach the socks through the docker host LAN ip, but it IS reachable from within other containers in the same network.

What's still weird, is that I can use the socks5 service with my firefox but NOT with curl

```
$ curl --proxy socks5://192.192.0.201:1081 test.de
curl: (28) Failed to connect to 192.192.0.201 port 1081 after 135033 ms: Couldn't connect to server
```

It works now but this is really weird.
